from selenium.webdriver.common.by import By

login_locator = (By.XPATH, '//input[@data-test="username"]')
password_locator = (By.XPATH, '//input[@data-test="password"]')
login_button_locator = (By.XPATH, '//input[@data-test="login-button"]')
login_error_message_locator = (By.XPATH, '//div[@class="error-message-container error"]')
logout_button_locator = (By.XPATH, '//a[@id="logout_sidebar_link"]')
burger_menu_button_locator = (By.XPATH, '//button[@id="react-burger-menu-btn"]')
burger_menu_locator = (By.XPATH, '//div[@class="bm-menu"]')
burger_menu_close_locator = (By.XPATH, '//button[@id="react-burger-cross-btn"]')
burger_about_button_locator = (By.XPATH, '//a[@id="about_sidebar_link"]')
burger_all_items_button_locator = (By.XPATH, '//a[@id="inventory_sidebar_link"]')
burger_reset_button_locator = (By.XPATH, '//a[@id="reset_sidebar_link"]')
add_to_cart_backpack_locator_one = (By.XPATH, '//button[@id="add-to-cart-sauce-labs-backpack"]')
cart_store_button_locator = (By.XPATH, '//a[@class="shopping_cart_link"]')
remove_saucelab_backpack_cart_locator = (By.XPATH, '//button[@class="btn btn_secondary btn_small cart_button"]')
header_secondary_container_products = (By.XPATH, '//span[contains(text(), "Products")]')
header_secondary_container_cart = (By.XPATH, '//span[contains(text(), "Your Cart")]')
cart_button_continue_shopping = (By.XPATH, '//button[@id="continue-shopping"]')
cart_checkout_button = (By.XPATH, '//button[@id="checkout"]')
header_secondary_container_checkout = (By.XPATH, '//span[contains(text(), "Checkout: Your Information")]')
checkout_cancel_button = (By.XPATH, '//button[@id="cancel"]')
checkout_continue_button = (By.XPATH, '//input[@id="continue"]')
checkout_first_name_field = (By.XPATH, '//input[@id="first-name"]')
checkout_last_name_field = (By.XPATH, '//input[@id="last-name"]')
checkout_postal_code_field = (By.XPATH, '//input[@id="postal-code"]')
overview_header = (By.XPATH, '//span[contains(text(), "Checkout: Overview")]')
checkout_error_container = (By.XPATH, '//div[@class="error-message-container error"]')
overview_cancel_button = (By.XPATH, '//button[@id="cancel"]')
overview_finish_button = (By.XPATH, '//button[@id="finish"]')
complete_page_back = (By.XPATH, '//button[@id="back-to-products"]')
complete_header = (By.XPATH, '//span[contains(text(), "Checkout: Complete!")]')