# site link
site_url = 'https://www.saucedemo.com/'

# xpath locators
login_locator = '//input[@data-test="username"]'
password_locator = '//input[@data-test="password"]'
login_button_locator = '//input[@data-test="login-button"]'
logo_locator = '//div[@class="app_logo"]'
t_shirt_locator_1 = '//div[contains(text(), "Test.allTheThings() T-Shirt (Red)")]'
t_shirt_locator_2 = '//div[contains(text(), "Sauce Labs Bolt T-Shirt")]'
product_label_locator = '//div[@class="header_secondary_container"]'
button_t_shirt_locator_1 = '//button[@id="add-to-cart-test.allthethings()-t-shirt-(red)"]'
button_t_shirt_locator_2 = '//button[@id="add-to-cart-sauce-labs-bolt-t-shirt"]'
button_backpack_locator = '//button[@id="add-to-cart-sauce-labs-backpack"]'
button_bike_lights_locator = '//button[@id="add-to-cart-sauce-labs-bike-light"]'
button_jacket_locator = '//button[@id="add-to-cart-sauce-labs-fleece-jacket"]'
button_onesie_locator = '//button[@id="add-to-cart-sauce-labs-onesie"]'
sidebar_all_items_locator = '//a[@id="inventory_sidebar_link"]'
sidebar_about_locator = '//a[@id="about_sidebar_link"]'
sidebar_logout_locator = '//a[@id="logout_sidebar_link"]'
sidebar_reset_locator = '//a[@id="reset_sidebar_link"]'
sidebar_close_button = '//button[@id="react-burger-cross-btn"]'
footer_text_locator = '//div[@class="footer_copy"]'
drop_list_locator = '//select[@class="product_sort_container"]'
option_az_locator = '//option[@value="az"]'
option_za_locator = '//option[@value="za"]'
option_low_high_locator = '//option[@value="lohi"]'
option_high_low_locator = '//option[@value="hilo"]'
shopping_cart_locator = '//a[@class="shopping_cart_link"]'
button_continue_shopping_locator = '//button[@data-test="continue-shopping"]'
button_checkout_locator = '//button[@data-test="checkout"]'
footer_image_locator = '//img[@alt="Swag Bot Footer"]'
footer_social_locator = '//ul[@class="social"]'
cart_desc_label_locator = '//div[@class="cart_desc_label"]'
cart_quantity_label_locator = '//div[@class="cart_quantity_label"]'

# css locators (may repeat from xpath)
cart_quantity_label_locator_css = '.cart_quantity_label'
cart_desc_label_locator_css = '.cart_desc_label'
button_continue_shopping_locator_css = '#continue-shopping'
button_checkout_locator_css = '#checkout'
burger_menu_button_css = '#react-burger-menu-btn'
shopping_cart_locator_css = '.shopping_cart_link'
app_logo_css = '.app_logo'
sidebar_about_locator_css = '#about_sidebar_link'
sidebar_logout_locator_css = '#logout_sidebar_link'
sidebar_reset_locator_css = '#reset_sidebar_link'
sidebar_close_button_css = '#react-burger-cross-btn'
login_locator_css = '#user-name'
password_locator_css = '#password'
login_button_locator_css = '#login-button'
footer_locator_css = '.footer'
header_peek_locator_css = '.peek'

# login info
login = 'standard_user'
password = 'secret_sauce'
